### ISSUE TITLE
Is the imgui test engine and test suite framework compatible with Google Test?

### ISSUE THREAD

**Issue by rudycazabon** [ocornut/imgui_test_engine#10]
Don't know where to send this question - is the ImGUI test engine and test suite compatible or interoperable with Google Test (gtest)?

If this is possible where or how might this be possible?

**Comment by PathogenDavid** [comment]
It'd be helpful to know what functionality from GoogleTest you'd expect to interoperate with the test engine.

As far as the actual tests and asserts go: I would say no. You should treat the Dear ImGui Test Engine as its own testing framework.

As far as ancillary functionality like gMock goes: I imagine it probably works, but I think you should look at the Test Engine as being designed for system/integration tests rather than unit tests. (You can of course mock in system tests, but in my experience it's generally frowned upon.)

If your goal is to aggregate results (IE: for CI), the Test Engine supports [exporting the JUnit XML report format](https://github.com/ocornut/imgui_test_engine/wiki/Exporting-Results). (GoogleTest supports [a variant of this format](https://google.github.io/googletest/advanced.html#generating-an-xml-report), so your existing tools might already support it.)

**Comment by ocornut** [comment]
Closing as answered, thanks David!
